### ISSUE TITLE
SSR+访问控制问题

### ISSUE THREAD

**Issue by kongzheng333** [iyuangang/openwrt#1]
首先感谢您的项目 实乃原生简洁党的福音 现在发现一个问题 在SSR+访问控制中的黑白名单中输入域名保存会显示没有待保存的更改 不生效 有时间的话您可以研究下 我用的版本是action最新编译的x86 64

**Comment by iyuangang** [comment]
> 首先感谢您的项目 实乃原生简洁党的福音 现在发现一个问题 在SSR+访问控制中的黑白名单中输入域名保存会显示没有待保存的更改 不生效 有时间的话您可以研究下 我用的版本是action最新编译的x86 64

感谢支持，同为原生简洁党。握手。刚验证了一下，修改黑白名单后，点击Save&Apply 可保存。L大更新下一个版本，测试稳定后立刻更新。

**Comment by iyuangang** [comment]
`OpenWrt 19.07.2` 新稳定版加L大新特性集成 `ssr plus +` 已 `release`
欢迎使用。
