### ISSUE TITLE
为啥我我编译的版本在vm上运行不显示“交换机”页面

### ISSUE THREAD

**Issue by eskimokk** [iyuangang/openwrt#11]
请教：为啥我我编译的版本在vm上运行不显示“交换机”页面。
vmware esxi下的，没有“交换机”页面卡。一般是啥情况？

**Comment by iyuangang** [comment]
把有交换机的版本 `.config` 找到，跟你的 `.config` 做一下对比。

**Comment by eskimokk** [comment]
Edit your /etc/config/network

add
{{{config 'switch' 'DEVICES'

option 'enable' '1'
option 'enable_vlan' '1'
option 'reset' '1'

}}}
