### ISSUE TITLE
luci报错

### ISSUE THREAD

**Issue by Kevin19941121** [iyuangang/openwrt#16]
自编译 输入ip 可以看到输入密码的界面 输入密码后
显示这个？
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'admin_status/index'.
A runtime error occurred: [string "/usr/lib/lua/luci/view/admin_status/index.h..."]:4: module 'luci.tools.status' not found:
	no field package.preload['luci.tools.status']
	no file './luci/tools/status.lua'
	no file '/usr/share/lua/luci/tools/status.lua'
	no file '/usr/share/lua/luci/tools/status/init.lua'
	no file '/usr/lib/lua/luci/tools/status.lua'
	no file '/usr/lib/lua/luci/tools/status/init.lua'
	no file './luci/tools/status.so'
	no file '/usr/lib/lua/luci/tools/status.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	[string "/usr/lib/lua/luci/view/admin_status/index.h..."]:4: in main chunk
stack traceback:
	[C]: in function 'n'
	/usr/lib/lua/luci/template.lua:55: in function </usr/lib/lua/luci/template.lua:47>
	(tail call): ?
	/usr/lib/lua/luci/dispatcher.lua:843: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:815: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:411: in function </usr/lib/lua/luci/dispatcher.lua:410>

**Comment by iyuangang** [comment]
我测试了最新的版本，没有问题。你看看先在我的模版基础上修改一下。别一下改太多。

**Comment by Kevin19941121** [comment]
好的 好的 十分感激您！
