### ISSUE TITLE
能否将ssrplus升级成最新版本

### ISSUE THREAD

**Issue by Kevin19941121** [iyuangang/openwrt#17]
![image](https://user-images.githubusercontent.com/65764770/83259562-dff4c100-a1ea-11ea-8d61-9e5b73bce325.png)
![image](https://user-images.githubusercontent.com/65764770/83259581-e71bcf00-a1ea-11ea-8d27-4d1115715706.png)
对比了下lean的hello world发现版本号还差一点点
不知道是不是怕不兼容 有意不升级？

**Comment by iyuangang** [comment]
今天下午已经升级了178-5 了。目前使用正常。
<img width="951" alt="图片" src="https://user-images.githubusercontent.com/20696803/83265329-f0f60000-a1f3-11ea-90b5-2e5c3e60f42d.png">

<img width="984" alt="图片" src="https://user-images.githubusercontent.com/20696803/83265455-1daa1780-a1f4-11ea-99a8-f433929ed4d6.png">

**Comment by Kevin19941121** [comment]
非常支持！很棒！
