### ISSUE TITLE
我可以在openwrt 19.07.4上使用ssr plus吗

### ISSUE THREAD

**Issue by predators46** [iyuangang/openwrt#25]
我可以在官方openwrt分支的openwrt 19.07.4上使用ssr plus吗？ 我已经在官方openwrt 19.07.4上尝试过它，shadowsocks / shadowsocksR和v2ray已经处于活动状态，但我无法访问Internet。可以ssr plus不能在正式的openwrt 19.07.4中使用

**Comment by iyuangang** [comment]
可以使用，本项目默认集成ssr plus，编译完成可直接使用。
[最新Releases](https://github.com/iyuangang/openwrt/releases/tag/openWRT19.07.4)

**Comment by predators46** [comment]
> 可以使用，本项目默认集成ssr plus，编译完成可直接使用。
> [最新Releases](https://github.com/iyuangang/openwrt/releases/tag/openWRT19.07.4)

为什么ssr plus不能在官方的openwrt 19.07.4中使用，系统上有区别吗？

**Comment by iyuangang** [comment]
这就是官方openwrt 19.07.4 源码+ ssr plus 编译系统。做了一些适配。

**Comment by predators46** [comment]
> 这就是官方openwrt 19.07.4 源码+ ssr plus 编译系统。做了一些适配。

如果我知道什么已更改以及需要修改哪些文件

**Comment by iyuangang** [comment]
可以查看最近几次提交内容

**Comment by predators46** [comment]
> 可以查看最近几次提交内容

`     CC [M]  /home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/sfe_ipv4.o
/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/sfe_ipv4.c: In function 'sfe_ipv4_recv_udp':
/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/sfe_ipv4.c:1478:5: error: 'struct sk_buff' has no member named 'fast_forwarded'
  skb->fast_forwarded = 1;
     ^~
/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/sfe_ipv4.c: In function 'sfe_ipv4_recv_tcp':
/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/sfe_ipv4.c:2052:5: error: 'struct sk_buff' has no member named 'fast_forwarded'
  skb->fast_forwarded = 1;
     ^~
scripts/Makefile.build:326: recipe for target '/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/sfe_ipv4.o' failed
make[5]: *** [/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/sfe_ipv4.o] Error 1
Makefile:1550: recipe for target '_module_/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe' failed
make[4]: *** [_module_/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe] Error 2
make[4]: Leaving directory '/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/linux-4.14.195'
Makefile:80: recipe for target '/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/.built' failed
make[3]: *** [/home/azurevps46/openwrt-openWRT19.07.4/build_dir/target-mipsel_24kc_musl/linux-ramips_mt7620/shortcut-fe/.built] Error 2
make[3]: Leaving directory '/home/azurevps46/openwrt-openWRT19.07.4/package/lean/shortcut-fe'
time: package/lean/shortcut-fe/compile#1.27#0.56#1.65
package/Makefile:111: recipe for target 'package/lean/shortcut-fe/compile' failed
make[2]: *** [package/lean/shortcut-fe/compile] Error 2
make[2]: Leaving directory '/home/azurevps46/openwrt-openWRT19.07.4'
package/Makefile:107: recipe for target '/home/azurevps46/openwrt-openWRT19.07.4/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/azurevps46/openwrt-openWRT19.07.4/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/azurevps46/openwrt-openWRT19.07.4'
/home/azurevps46/openwrt-openWRT19.07.4/include/toplevel.mk:225: recipe for target 'world' failed `
