### ISSUE TITLE
请问要同步你的更新，该怎么操作

### ISSUE THREAD

**Issue by jazkim** [iyuangang/openwrt#3]
我Fork 了项目后，可以成功出固件，在我的树莓派3上也可以正常运行。
但是我发现你更新项目后我Fork 的这边没有同步，是不是要做什么操作才能同步？
才开始用，可能问题很小白，请见谅。

**Comment by iyuangang** [comment]
方法有以下几种：
1. 在网页上`Clone or download` 这个绿色按钮下方有个 `Pull request` 点击它。箭头左边选择你的Fork ，右边选择我这边的项目，点击 `Create pull request` 提交就可以。
2. 有Actions 可以自动同步上游，我去找找发给你附在下面。
