### ISSUE TITLE
55r无法正常添加订阅

### ISSUE THREAD

**Issue by kongzheng333** [iyuangang/openwrt#4]
action编译的最新x86版 55r日志报错如下

	[C]: ?
	/usr/share/shadowsocksr/subscribe.lua:10: in main chunk
	[C]: in function 'require'
stack traceback:
	no file '/usr/lib/lua/loadall.so'
	no file '/usr/lib/lua/uci.so'
	no file './uci.so'
	no file '/usr/lib/lua/uci/init.lua'
	no file '/usr/lib/lua/uci.lua'
	no file '/usr/share/lua/uci/init.lua'
	no file '/usr/share/lua/uci.lua'
	no file './uci.lua'
	no field package.preload['uci']
/usr/bin/lua: /usr/share/shadowsocksr/subscribe.lua:10: module 'uci' not found:

看描述是uci出了问题

**Comment by iyuangang** [comment]
可安装 `luci-compat` 或编译自定义选项时添加 `CONFIG_PACKAGE_luci-compat=y`

来自官方 [Release Note](https://openwrt.org/releases/19.07/notes-19.07.2)
The new version of LuCI, the integrated web interface for OpenWrt, implements client-side rendering of views. This improves performance by offloading some work that was done on the device (Lua code) to the client browser (Javascript code)

The LuCI ecosystem is large, and not all LuCI apps have been adapted to this change, which may result in crashes involving `cbi.lua`. In that case, install the `luci-compat` package.

**Comment by iyuangang** [comment]
Sorry, 我的错，没仔细看问题。
临时解决方案为用release 3 gold version 编译。
具体问题正在排查。

**Comment by iyuangang** [comment]
问题找到了，测试通过，马上修复。
但是意味着以后不能从lean package 取源码。
需要从这边clone 修改后的源码。

**Comment by yfdoor** [comment]
最近的更新似乎还是没有修复这个文通

> 问题找到了，测试通过，马上修复。
> 但是意味着以后不能从lean package 取源码。
> 需要从这边clone 修改后的源码。

嗯，他那边还是没有修复这个兼容问题

**Comment by iyuangang** [comment]
> 最近的更新似乎还是没有修复这个文通
> 
> > 问题找到了，测试通过，马上修复。
> > 但是意味着以后不能从lean package 取源码。
> > 需要从这边clone 修改后的源码。
> 
> 嗯，他那边还是没有修复这个兼容问题

最近L大那边一直在添加新功能，每个版本都有bug，等稳定了再发布一个版本。我这边的就是追求稳定。
