### ISSUE TITLE
关于本土化的咨询

### ISSUE THREAD

**Issue by yfdoor** [iyuangang/openwrt#6]
没找到合适的地方，来你这里讨扰下 : )
有时候编译出来的固件luci界面菜单里的插件名称还是英文，但是插件里面的界面已经是中文。
这个package 以装CONFIG_LUCI_LANG_zh_Hans=y

不知道哪里还需要修改下

**Comment by iyuangang** [comment]
这个应该是翻译不全的问题。
比如 `adbybyplus` 的中文翻译文件,对应位置在 `package/lean/luci-app-adbyby-plus/po/zh-cn/adbyby.po`
里面有多个翻译不对应，使用过程中就有部分翻译无法显示中文。
如果有空可以自己修改，验证通过后提交。
