### ISSUE TITLE
好像无法使用部分官方源安装，会报Kernel版本不对

### ISSUE THREAD

**Issue by wayne651x** [iyuangang/openwrt#8]
大版本号是对的，但小版本号不兼容，汇报以下错误。

The installed version of package kernel is not compatible, require 4.14.171-1-e1dd7676… while 4.14.171-1-a60e1dec… is installed.

**Comment by iyuangang** [comment]
请问使用的哪个版本？
安装的软件包是？

**Comment by wayne651x** [comment]
直接用了这个仓库Release里的最新版（19.07.2）openwrt-x86-64-combined-ext4.img.gz

安装完后使用 System => Software 里面的方式安装的。因为我用来做软路由的机子是单网口，所以我需要装一个USB网卡，在装 kmod-usb-core 时报了这个错。其他有些可以装，有些也会报这个错。

我自己试过官方下的 19.07.2 的镜像可以装。我对比了下时间，官方说 19.07.2 是3月6号发布的。但我看你这边Release包的时间好像早于它。

**Comment by iyuangang** [comment]
~~看了下，确实比官方早，刚才更新了 `4.14.172` 等 `github actions` 跑完我再测试下。~~

**Comment by wayne651x** [comment]
好的，感谢~

**Comment by iyuangang** [comment]
找到原因了。
不是 `kernel` 的问题，是个人编译后指纹与官方不符，需要替换为官方指纹。
修改方法如下 
`vi /usr/lib/opkg/status`
在 `vi` 的 `normal` 模式下替换`a60e1decc7262b7aff1e5f054fe9598f` 为官方指纹`e1dd7676581672f6f0bdb1363506dee1`
先输入英文小写冒号`:`
再把下面语句粘贴到冒号后面
`%s/a60e1decc7262b7aff1e5f054fe9598f/e1dd7676581672f6f0bdb1363506dee1/g`
按回车，完成替换操作。
<img width="597" alt="图片" src="https://user-images.githubusercontent.com/20696803/77821637-bce45d00-7126-11ea-96ab-7bd954cc29e8.png">

再输入`:wq` 保存
`:wq`
更新一下就可以安装了。
<img width="592" alt="图片" src="https://user-images.githubusercontent.com/20696803/77821678-0c2a8d80-7127-11ea-91fa-bbf230864db5.png">

**Comment by wayne651x** [comment]
亲测有效。单子可以关了 :D

**Comment by 123456zz-del** [comment]
太棒啦太棒啦，感谢大神，终于解决了
